### ISSUE TITLE
gcalcli init error, datetimeparser error

### ISSUE THREAD

**Issue by bjornasm** [insanum/gcalcli#142]
I get the following error when typing gcalcli, gcalcli --help or whatever:

```
Traceback (most recent call last):
File "/usr/bin/gcalcli", line 392, in <module>
  class gcalcli:
 File "/usr/bin/gcalcli", line 410, in gcalcli
 dateParser    = DateTimeParser()
 File "/usr/bin/gcalcli", line 335, in __init__
  self.pdtCalendar = parsedatetime.Calendar();
  File "/usr/lib/python2.7/dist-packages/parsedatetime/__init__.py", line 216, in __init__
   self.ptc = Constants()
   File "/usr/lib/python2.7/dist-packages/parsedatetime/__init__.py", line 1733, in __init__
   self.locale = pdtLocales['icu'](self.localeID)
    File "/usr/lib/python2.7/dist-packages/parsedatetime/pdt_locales.py", line 151, in __init__
     self.icu = pyicu.Locale(localeID)
     icu.InvalidArgsError: (<type 'icu.Locale'>, '__init__', (None,))
```

**Comment by HollowProductions** [comment]
I've tried the upgrade parsedatetime and it it still hasn't fixed it for me.
