### ISSUE TITLE
Invalid strftime format string on Windows

### ISSUE THREAD

**Issue by njoyard** [insanum/gcalcli#177]
When querying events on Windows (win7 x64 with python 2.7.9) I get the following error when doing any operation that queries events:

```
C:\>python c:\bin\Python27\Scripts\gcalcli --calendar TestCLI search X
Traceback (most recent call last):
  File "c:\bin\Python27\Scripts\gcalcli", line 2457, in <module>
    BowChickaWowWow()
  File "c:\bin\Python27\Scripts\gcalcli", line 2308, in BowChickaWowWow
    gcal.TextQuery(stringToUnicode(args[1]))
  File "c:\bin\Python27\Scripts\gcalcli", line 1573, in TextQuery
    self._IterateEvents(self.now, eventList, yearDate=True)
  File "c:\bin\Python27\Scripts\gcalcli", line 1453, in _IterateEvents
    tmpDayStr = event['s'].strftime(dayFormat)
ValueError: Invalid format string
```

Adding a few traces to the program, turns out event['s'] is valid but dayFormat = '%F' is not. Not sure whether this is a Python version issue... ?

**Comment by njoyard** [comment]
Okay, so after a bit of research turns out "%F" is nonstandard and should be replaced by its equivalent "%Y-%m-%d". Works like a charm now.
