### ISSUE TITLE
Can't import certain recurring events that have ended

### ISSUE THREAD

**Issue by EqUaTe** [insanum/gcalcli#181]
I have an ICS file that I am trying to import. Through various things I have stripped it down and have a single event that triggers an error when importing.

BEGIN:VCALENDAR
PRODID:-//Kerio Technologies//Kerio Connect//EN
METHOD: PUBLISH
VERSION:2.0
X-WR-CALNAME:Calendar
BEGIN:VEVENT
ORGANIZER;CN="person.1";SCHEDULE-STATUS=1.1:mailto:person.1@example.com
UID:C8E0DADD-59D0-471E-8094-73D7BC7AF439
CREATED:20111219T092337Z
CLASS:PUBLIC
DTSTAMP:20120110T153945Z
RRULE:FREQ=WEEKLY;UNTIL=20120109T235959;BYDAY=TU
DTEND:20111220T164500
LOCATION:Main Meeting Room
DESCRIPTION:https://wiki.example.com/wiki/index.php/Agenda_for_Engineering_Meeting\n\n
SEQUENCE:11
SUMMARY:Engineering meeting
DTSTART:20111220T160000
ATTENDEE;RSVP=TRUE;CN="person.2";CUTYPE=INDIVIDUAL:mailto:person.2@example.com
ATTENDEE;RSVP=TRUE;CN="person.3";CUTYPE=INDIVIDUAL:mailto:person.3@example.com
ATTENDEE;RSVP=TRUE;CN="person.4";CUTYPE=INDIVIDUAL:mailto:person.4@example.com
ATTENDEE;RSVP=TRUE;CN="Main Meeting Room";CUTYPE=ROOM:mailto:Main_Meeting_Room@example.com
ATTENDEE;RSVP=TRUE;CN="Chris Taylor";CUTYPE=INDIVIDUAL:mailto:chris.taylor@example.com
END:VEVENT
END:VCALENDAR

If I adjust the RRULE line and remove the UNTIL part, it imports successfully, though this is obviously not what I want to do. I have a number of other recurring events that have ended that I also wish to import, I have not yet checked to see if any of these work.
Does anyone have any thoughts on what is going on?

Here is the output from gcalcli when trying to import the above:
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 4, in <module>
    __import__('pkg_resources').run_script('gcalcli==3.2', 'gcalcli')
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 646, in run_script
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 1574, in run_script
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gcalcli-3.2-py2.7.egg/EGG-INFO/scripts/gcalcli", line 2503, in <module>
    
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gcalcli-3.2-py2.7.egg/EGG-INFO/scripts/gcalcli", line 2490, in BowChickaWowWow
    
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gcalcli-3.2-py2.7.egg/EGG-INFO/scripts/gcalcli", line 2007, in ImportICS
    
  File "/usr/local/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/http.py", line 723, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/chris.taylor%40example.com/events?alt=json returned "Invalid Value">

**Comment by tresni** [comment]
Unfortunately this is the API stopping the import and it doesn't really give us any useful information from what I can see when I mitmproxy this stuff...  The Invalid Value is on the UNTIL date it seems so it just doesn't like you importing things in the past for some reason.  I have no idea why...  I'll leave this open in case anyone has any insight.
