### ISSUE TITLE
gcalcli errors raspberry pi raspbian

### ISSUE THREAD

**Issue by megrimm** [insanum/gcalcli#188]
Hello,

Stock raspberry pi / raspbian:

$ sudp apt-get install gcalcli
$ gcalcli --user NAME --pw PASS agenda

Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 1524, in <module>
    BowChickaWowWow()
  File "/usr/bin/gcalcli", line 1426, in BowChickaWowWow
    borderColor=borderColor)
  File "/usr/bin/gcalcli", line 345, in __init__
    self.allCals = self.gcal.GetAllCalendarsFeed()
  File "/usr/lib/python2.7/dist-packages/gdata/calendar/service.py", line 81, in GetAllCalendarsFeed
    return self.Get(uri, converter=gdata.calendar.CalendarListFeedFromString)
  File "/usr/lib/python2.7/dist-packages/gdata/service.py", line 1107, in Get
    'reason': server_response.reason, 'body': result_body}
gdata.service.RequestError: {'status': 403, 'body': '<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n', 'reason': 'Forbidden'}

$ gcalcli --user NAME
Password: 
Error: no command (--help)

root@raspberrypi:~# gcalcli --version
gcalcli v2.1 (Eric Davis)

thoughts?

Thanks!
m,

**Comment by insanum** [comment]
This is an old version of gcalcli using an old version of the Google gdata API. You need to upgrade.
