### ISSUE TITLE
Can’t persist authorisation

### ISSUE THREAD

**Issue by jezen** [insanum/gcalcli#196]
Trying to authorise with Google. Not going so well.

~~~shell
➜  ~  gcalcli agenda
WARNING:root:This function, oauth2client.tools.run(), and the use of the gflags library are deprecated and will be removed in a future version of the library.
Failed to start a local webserver listening on either port 8080
or port 9090. Please check your firewall settings and locally
running programs that may be blocking or using those ports.

Falling back to --noauth_local_webserver and continuing with
authorization.

Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Furlshortener&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=232867676714.apps.googleusercontent.com&access_type=offline

Enter verification code: 4/dLjgn11nxSds*****redacted*****lJaofHcfAPORs
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 2555, in <module>
    BowChickaWowWow()
  File "/usr/local/bin/gcalcli", line 2406, in BowChickaWowWow
    gcal.AgendaQuery()
  File "/usr/local/bin/gcalcli", line 1665, in AgendaQuery
    eventList = self._SearchForCalEvents(start, end, None)
  File "/usr/local/bin/gcalcli", line 1584, in _SearchForCalEvents
    work = self._CalService().events().\
  File "/usr/local/bin/gcalcli", line 684, in _CalService
    http=self._GoogleAuth())
  File "/usr/local/bin/gcalcli", line 673, in _GoogleAuth
    storage)
  File "/Library/Python/2.7/site-packages/oauth2client-1.4.11-py2.7.egg/oauth2client/util.py", line 137, in positional_wrapper
  File "/Library/Python/2.7/site-packages/oauth2client-1.4.11-py2.7.egg/oauth2client/old_run.py", line 153, in run
  File "/Library/Python/2.7/site-packages/oauth2client-1.4.11-py2.7.egg/oauth2client/util.py", line 137, in positional_wrapper
  File "/Library/Python/2.7/site-packages/oauth2client-1.4.11-py2.7.egg/oauth2client/client.py", line 1982, in step2_exchange
  File "/Library/Python/2.7/site-packages/httplib2-0.9.1-py2.7.egg/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Library/Python/2.7/site-packages/httplib2-0.9.1-py2.7.egg/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Library/Python/2.7/site-packages/httplib2-0.9.1-py2.7.egg/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/Library/Python/2.7/site-packages/httplib2-0.9.1-py2.7.egg/httplib2/__init__.py", line 1036, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "/Library/Python/2.7/site-packages/httplib2-0.9.1-py2.7.egg/httplib2/__init__.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 520, in __init__
    self._context.load_verify_locations(ca_certs)
IOError: [Errno 13] Permission denied
~~~

**Comment by tresni** [comment]
Seems like the ca_certs bundle got installed with incorrect permissions.  See [this thread](http://stackoverflow.com/questions/27870024/google-gmail-api-installed-app-shows-ioerror-13-from-module-ssl-py-w-o-sudo) on stackoverflow.

**Comment by jezen** [comment]
@tresni Ah, in my case I had to change the permissions of `~/.gcalcli_oauth`.

I did a `sudo chmod 777 ~/.gcalcli_oauth`, and now it’s working. Or did I do something stupid now?

**Comment by tresni** [comment]
That's odd given that's definitely not where it appears to be throwing the error.  Only drawback to 777 versus the standard default is that *anyone* with access to your system can act on your calendar.

**Comment by apolinux** [comment]
I had the same issue and I resolved with this solution:

sudo chmod go+r  /usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg/httplib2/cacerts.txt

I followed the instructions on this stackoverfolow [link](http://stackoverflow.com/questions/27870024/google-gmail-api-installed-app-shows-ioerror-13-from-module-ssl-py-w-o-sudo) but even installing the libs from linux system it is not enough.
