### ISSUE TITLE
Can't run gcalcli

### ISSUE THREAD

**Issue by metalhead6666** [insanum/gcalcli#200]
When I try to run "gcalcli agenda", I have this error and don't know how to resolve it.
Also, I'm sure that is using python 2 (2.7.6)
```
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 5, in <module>
    pkg_resources.run_script('gcalcli==3.3', 'gcalcli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/gcalcli-3.3-py2.7.egg/EGG-INFO/scripts/gcalcli", line 518, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/gcalcli-3.3-py2.7.egg/EGG-INFO/scripts/gcalcli", line 531, in gcalcli
    
  File "/usr/local/lib/python2.7/dist-packages/gcalcli-3.3-py2.7.egg/EGG-INFO/scripts/gcalcli", line 440, in __init__
    
  File "/usr/lib/python2.7/dist-packages/parsedatetime/__init__.py", line 216, in __init__
    self.ptc = Constants()
  File "/usr/lib/python2.7/dist-packages/parsedatetime/__init__.py", line 1733, in __init__
    self.locale = pdtLocales['icu'](self.localeID)
  File "/usr/lib/python2.7/dist-packages/parsedatetime/pdt_locales.py", line 151, in __init__
    self.icu = pyicu.Locale(localeID)
icu.InvalidArgsError: (<type 'icu.Locale'>, '__init__', (None,))
```

**Comment by metalhead6666** [comment]
It was a problem of parsedatetime

**Comment by HollowProductions** [comment]
how did you fix it?  I've upgraded my parsedatetime, i have the 1.2 version, and it still won't work.  I've been through these forums for a good 7 hours now between two days and I can't get it to work.

**Comment by metalhead6666** [comment]
I installed the last version of parsedatetime with pip and it worked perfectly
