### ISSUE TITLE
Modules, VersionConflict error

### ISSUE THREAD

**Issue by BrendaFdez** [insanum/gcalcli#202]
I'm pretty much a complete noob. I installed downloading source via git and running the install script. Now when I try to run gcalcli, I get the following output. I'm not even sure what the error is, but I can't use it. 

```
brenda@debian:~$ gcalcli  list
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 4, in <module>
    __import__('pkg_resources').run_script('gcalcli==3.3', 'gcalcli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (pyasn1 0.1.7 (/usr/lib/python2.7/dist-packages), Requirement.parse('pyasn1>=0.1.8'))
```

**Comment by BrendaFdez** [comment]
For some reason I had tried installing dependences with pip and thought they had installed correctly. 

I tried installing packages python-gflags and python-dateutil from debian repos and that solved the issue. It's working correctly now.
