### ISSUE TITLE
`remind` should output url when using --details=all

### ISSUE THREAD

**Issue by fedemp** [insanum/gcalcli#238]
My calendar is full of meeting in hangouts, so I have a cron job  for `gcalcli remind`.

`gcalci --details=url agenda` actually shows the Link and Hangout Link.

I would like `remind` to output these two too so I can click in the notification and open the link.

**Comment by tresni** [comment]
The above reference commit not only allows `--details url` but all `--details` options to be specified.  Uses the same output ordering as agenda/search (calendar, url, location, attendee, attachments, length, reminders, email, description). YMMV but it should work :)  Feel free to checkout the branch, but be aware it's on the new 4.0 base which has a lot of changes from 3.3/3.4

I'll likely include it in the next alpha release of 4.0

**Comment by grugnog** [comment]
Tested this out and it's working for me. My use case is using the script below to auto open hangout windows the minute before they are scheduled:
```
#!/usr/bin/env bash
RESULT=$(gcalcli remind --details url 2 "echo %s")
echo $RESULT | head -n1 | cut -d" " -f1 | grep -q $(date +'%l:%M%P' -d "1 mins")
if [[ $? == 1 ]]; then
  exit 1
fi
URL=$(echo $RESULT | sed -e "s/.*Hangout: \([^ ]*\).*/\1/g")
if [[ -z "${URL}" ]]; then
  exit 2
fi
google-chrome --app="${URL}"
```

**Comment by kurazsi** [comment]
Hello. I'm trying to create a cron job for gcalcli but it's not working for me.
I'm running Xubuntu 16.10 with i3wm and configured and i use gcalcli v3.4.0 (Eric Davis, Brian Hartvigsen)

I used at first using crontab -e the task to call "gcalcli remind 10"
BUT no notification apears.
Tested the command from console and it works.

Then i edited /etc/crontab , i'm seeing in the syslog that the crontab executed the commands 
BUT still no notification appears (using dunst as the notification service)

this is my crontab contents now:
# m    h dom mon dow   user              command
*/10 8-20  *   * 1-5   <my user name>  /usr/bin/gcalcli --calendar='xxxxxxx@xxxxxxx' remind 10 '/usr/bin/notify-send -u critical -a gcalcli %s'
*/10 8-20  *   * 1-5    <my user name>  /usr/bin/gcalcli --calendar='xxxxxxx@xxxxxxx'  remind 0  '/usr/bin/notify-send -u critical -a gcalcli %s'
*/10 8-20  *   * 1-5    <my user name>  /usr/bin/gcalcli --calendar='xxxxxxx@xxxxxxx'  remind 10 '/usr/bin/notify-send -u critical -a gcalcli %s'
*/10 8-20  *   * 1-5    <my user name>  /usr/bin/gcalcli --calendar='xxxxxxx@xxxxxxx'  remind 0  '/usr/bin/notify-send -u critical -a gcalcli %s'
*/10 8-20  *   * 1-5    <my user name>  /usr/bin/gcalcli --calendar='Team Meetings' remind 10 '/usr/bin/notify-send -u critical -a gcalcli %s'
*/10 8-20  *   * 1-5    <my user name>  /usr/bin/gcalcli --calendar='Team Meetings' remind 0  '/usr/bin/notify-send -u critical -a gcalcli %s'

if i execute the command in the console then it works.

PS: Should i use the call with the remind 0 if I want to be reminded right before the event starts, or is there a better way ?

**Comment by kurazsi** [comment]
UPDATED gcalcli to the version from the commit in this issue:
now if using "--details all", the call fails with: (--details url, works) 
gcalcli remind --details all 10 'echo %s'
Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 2564, in <module>
    BowChickaWowWow()
  File "/usr/bin/gcalcli", line 2551, in BowChickaWowWow
    gcal.Remind(FLAGS.minutes, FLAGS.cmd, use_reminders=FLAGS.use_reminders)
  File "/usr/bin/gcalcli", line 1915, in Remind
    attendees.add("%s: <%s>" % (
AttributeError: 'list' object has no attribute 'add'

**Comment by tresni** [comment]
ugh... my bad... should be `append` not `add`

**Comment by tresni** [comment]
e616daec6299c1a118c7d666c6bb6ff7e75e4e83 should fix that
