### ISSUE TITLE
Can't install gcalcli - wrong oauth2client version

### ISSUE THREAD

**Issue by billmaidment** [insanum/gcalcli#239]
After some recent updates on a Scientific Linux 6 machine, gcalcli stopped working, so I tried to re-install it. When I run python setup.py install I get the following error:
Installed /usr/lib/python2.6/site-packages/gcalcli-3.3.2-py2.6.egg
Processing dependencies for gcalcli==3.3.2
error: Installed distribution oauth2client 1.4.12 conflicts with requirement oauth2client>=2.0.0,<3

How do I find out what is causing this?

**Comment by sarsw** [comment]
Hi,

Same problem with me. It had been ok on Wheezy but installing on Jessie on the Pi3, Python 2.7.9 I got:

:pip install gcacli 
...
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (oauth2client 1.4.12 (/usr/local/lib/python2.7/dist-packages/oauth2client-1.4.12-py2.7.egg), Requirement.parse('oauth2client>=2.0.0,<3'))
:pip install gcacli ...  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve    raise VersionConflict(dist, req)
**pkg_resources.VersionConflict: (oauth2client 1.4.12 (/usr/local/lib/python2.7/dist-packages/oauth2client-1.4.12-py2.7.egg), Requirement.parse('oauth2client>=2.0.0,<3'))
**

Trying "python setup.py install" gives the same error as billmaidment.

Any ideas anybody?

Cheers, Steve

**Comment by billmaidment** [comment]
I believe the issue is caused by google_api_python_client-1.5.0 being installed in the "python setup.py install" process. I tried amending setup.py with
         'google-api-python-client<=1.4.2',
 but then I got the following errors:

/usr/lib/python2.6/site-packages/parsedatetime/pdt_locales/icu.py:16: DeprecationWarning: Module 'PyICU' is deprecated, import 'icu' instead'
  import PyICU as pyicu
Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 5, in <module>
    pkg_resources.run_script('gcalcli==3.3.2', 'gcalcli')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/gcalcli-3.3.2-py2.6.egg/EGG-INFO/scripts/gcalcli", line 520, in <module>
    class gcalcli:
  File "/usr/lib/python2.6/site-packages/gcalcli-3.3.2-py2.6.egg/EGG-INFO/scripts/gcalcli", line 533, in gcalcli
    dateParser = DateTimeParser()
  File "/usr/lib/python2.6/site-packages/gcalcli-3.3.2-py2.6.egg/EGG-INFO/scripts/gcalcli", line 442, in __init__
    self.pdtCalendar = parsedatetime.Calendar()
  File "/usr/lib/python2.6/site-packages/parsedatetime/__init__.py", line 271, in __init__
    self.ptc = Constants()
  File "/usr/lib/python2.6/site-packages/parsedatetime/__init__.py", line 2375, in __init__
    self.locale = get_icu(self.localeID)
  File "/usr/lib/python2.6/site-packages/parsedatetime/pdt_locales/icu.py", line 54, in get_icu
    rbnf = pyicu.RuleBasedNumberFormat(pyicu.URBNFRuleSetTag.SPELLOUT, icu)
AttributeError: 'module' object has no attribute 'URBNFRuleSetTag'

**Comment by billmaidment** [comment]
Oops. Wrong button.

**Comment by billmaidment** [comment]
pip uninstall pyicu got rid of the error messages and now gclacli is working OK with conky. I'm not sure if this will cause any other issues, but I'll close this now.
