### ISSUE TITLE
global name 'run' is not defined

### ISSUE THREAD

**Issue by some1563** [insanum/gcalcli#267]
hi guys im trying to get gcalcli to run on my arch system but it does not work

I 
`yaourt gcalcli-git from terminal`

and everything seems to go through fine

but when I 

`gcalcli agenda`

I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 2647, in <module>
    BowChickaWowWow()
  File "/usr/bin/gcalcli", line 2470, in BowChickaWowWow
    allDay=FLAGS.allday
  File "/usr/bin/gcalcli", line 613, in __init__
    self._GetCached()
  File "/usr/bin/gcalcli", line 738, in _GetCached
    self._CalService().calendarList().list())
  File "/usr/bin/gcalcli", line 694, in _CalService
    http=self._GoogleAuth())
  File "/usr/bin/gcalcli", line 676, in _GoogleAuth
    credentials = run(
NameError: global name 'run' is not defined
```

**Comment by tresni** [comment]
Pretty sure you are seeing #237 .  The new 4.0.0 alpha builds resolve this.
