### ISSUE TITLE
VTODO item causes upload failure

### ISSUE THREAD

**Issue by oneyb** [insanum/gcalcli#300]
Dear Eric,

With the following to-be-created ics file I can't import  with gcalcli:
```bash
cat  > org_gcalcli_import_fails.ics << endfile
BEGIN:VCALENDAR
VERSION:2.0
X-WR-CALNAME:OrgMode
PRODID:-//Moi//Emacs with Org mode//EN
X-WR-TIMEZONE:CEST
X-WR-CALDESC:
CALSCALE:GREGORIAN
BEGIN:VTODO
UID:TODO-0ad1d734-ae83-4159-9d1a-25288d71fdfd
DTSTAMP:20170527T181958Z
DTSTART:20170527T201900
SUMMARY:Stuff
CATEGORIES:todo
SEQUENCE:1
PRIORITY:5
STATUS:NEEDS-ACTION
END:VTODO
END:VCALENDAR
endfile
gcalcli --verbose --calendar brian.j.oney@googlemail.com import org_gcalcli_import_fails.ics 
```
I have:
```bash
$ pip show gcalcli
---
Name: gcalcli
Version: 3.4.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: google-api-python-client, httplib2, oauth2client, python-dateutil, python-gflags
```
```python
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 2647, in <module>
    BowChickaWowWow()
  File "/usr/local/bin/gcalcli", line 2634, in BowChickaWowWow
    gcal.ImportICS(FLAGS.verbose, FLAGS.dump, FLAGS.reminder, args[1])
  File "/usr/local/bin/gcalcli", line 2104, in ImportICS
    for ve in v.vevent_list:
  File "/usr/lib/pymodules/python2.7/vobject/base.py", line 477, in __getattr__
    raise exceptions.AttributeError, name
AttributeError: vevent_list
```
It looks like a problem creating the vobject object. Do you assume that all items are events (VEVENT and not VTODO)?

Other things work great! As a sidenote, I am trying to develop a workflow with (spac)emacs and org-mode. Cool tool you have developed! 

Thanks,
Brian

**Comment by tresni** [comment]
We expect there is a VEVENT yes. We don't currently have support for importing VTODOs. 

-- Brian
