### ISSUE TITLE
.gcalcli_oauth can't be a symbolic link

### ISSUE THREAD

**Issue by weekssj** [insanum/gcalcli#309]
I use a live operating system and symlink in my config files but gcalcli breaks if ~/.gcalcli_oauth is not a real file. Can gcalcli please be made to follow symbolic links? Thanks.

Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 2649, in <module>
    BowChickaWowWow()
  File "/usr/bin/gcalcli", line 2472, in BowChickaWowWow
    allDay=FLAGS.allday
  File "/usr/bin/gcalcli", line 614, in __init__
    self._GetCached()
  File "/usr/bin/gcalcli", line 740, in _GetCached
    self._CalService().calendarList().list())
  File "/usr/bin/gcalcli", line 696, in _CalService
    http=self._GoogleAuth())
  File "/usr/bin/gcalcli", line 674, in _GoogleAuth
    credentials = storage.get()
  File "/usr/lib/python2.7/dist-packages/oauth2client/client.py", line 409, in get
    return self.locked_get()
  File "/usr/lib/python2.7/dist-packages/oauth2client/file.py", line 56, in locked_get
    self._validate_file()
  File "/usr/lib/python2.7/dist-packages/oauth2client/file.py", line 44, in _validate_file
    'File: {0} is a symbolic link.'.format(self._filename))
oauth2client.file.CredentialsFileSymbolicLinkError: File: /home/xxx/.gcalcli_oauth is a symbolic link.

**Comment by tresni** [comment]
gcalcli isn't the one raising this error [oauth2client](https://github.com/google/oauth2client) is.  You'd need to raise a bug with them to get this resolved, my guess is this is a security measure though.
