### ISSUE TITLE
404 Error with gcalcli

### ISSUE THREAD

**Issue by mathomp4** [insanum/gcalcli#313]
All,

Until a few days ago, gcalcli worked just fine for me. Now, it dies with 404 errors. I tried upgrading gcalcli to both the latest master and latest branch I could find (argparse_over_gflags) and both give the same error. I've tried removing my ~/.gcalcli_oauth and re-authorizing, and Google doesn't complain there. But, if I run gcalcli, I get an error:

```
(1196)(argparse_over_gflags) $ ./gcalcli calw
Traceback (most recent call last):
  File "./gcalcli", line 2544, in <module>
    BowChickaWowWow()
  File "./gcalcli", line 2449, in BowChickaWowWow
    gcal.CalQuery(FLAGS.command, count=FLAGS.weeks, startText=FLAGS.start)
  File "./gcalcli", line 1787, in CalQuery
    eventList = self._SearchForCalEvents(start, end, None)
  File "./gcalcli", line 1643, in _SearchForCalEvents
    events = self._RetryWithBackoff(work)
  File "./gcalcli", line 634, in _RetryWithBackoff
    return method.execute()
  File "/home/mathomp4/.local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mathomp4/.local/lib/python2.7/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/..... returned "Not Found">
```
Am I missing something? An SSL Cert? Like I said, last week I think this all worked, today, crashes galore.

**Comment by mathomp4** [comment]
Ah! My search-fu finally worked and the solution was to run `gcalcli --refresh --nocache` and all is well.
