### ISSUE TITLE
Unicode characters not working for `agenda` with non-terminal output

### ISSUE THREAD

**Issue by michaelmhoffman** [insanum/gcalcli#335]
Steps to reproduce:

1. Add an event to a default calendar called `Birthday Extravaganza!! 🎈🎈` at 9 p.m.
2. `gcalcli --nocolor agenda 12am 11:59pm`
```Sat Feb 17   9:00pm  Birthday Extravaganza!! 🎈🎈```
3. `gcalcli agenda 9pm 11pm | cat`
```
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 2500, in <module>

Sat Feb 17    BowChickaWowWow()
  File "/usr/local/bin/gcalcli", line 2398, in BowChickaWowWow
    gcal.AgendaQuery(startText=FLAGS.start, endText=FLAGS.end)
  File "/usr/local/bin/gcalcli", line 1696, in AgendaQuery
    self._DisplayQueriedEvents(start, end)
  File "/usr/local/bin/gcalcli", line 1661, in _DisplayQueriedEvents
    self._IterateEvents(start, eventList, yearDate=yearDate)
  File "/usr/local/bin/gcalcli", line 1527, in _IterateEvents
    self._PrintEvent(event, prefix)
  File "/usr/local/bin/gcalcli", line 1216, in _PrintEvent
    PrintMsg(eventColor, fmt % (_u(tmpTimeStr), _u(self._ValidTitle(event).strip())))
  File "/usr/local/bin/gcalcli", line 407, in PrintMsg
    sys.stdout.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 35-36: ordinal not in range(128)
```

gcalcli v4.0.0a3 (Eric Davis, Brian Hartvigsen), Python 2.7.12, Linux 4.4.0-43-Microsoft on Windows Subsystem for Linux, Windows 10.0.16299.248

**Comment by michaelmhoffman** [comment]
Workaround is to set `PYTHONIOENCODING=utf8`.

1. `PYTHONIOENCODING=utf8 gcalcli agenda 9pm 11pm | cat`

```
Sat Feb 17   9:00pm  Birthday Extravaganza!! 🎈🎈
```

**Comment by jcrowgey** [comment]
Repro on current master

**Comment by jcrowgey** [comment]
I'm happy to reopen this if someone has ideas.
