### ISSUE TITLE
ValueError: unsupported pickle protocol: 3

### ISSUE THREAD

**Issue by GreatAnubis** [insanum/gcalcli#338]
`11:17  $ gcalcli list
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 2647, in <module>
    BowChickaWowWow()
  File "/usr/local/bin/gcalcli", line 2470, in BowChickaWowWow
    allDay=FLAGS.allday
  File "/usr/local/bin/gcalcli", line 613, in __init__
    self._GetCached()
  File "/usr/local/bin/gcalcli", line 729, in _GetCached
    self.cache = pickle.load(_cache_)
ValueError: unsupported pickle protocol: 3
`

I'm getting this trying to list calendars. 
I'm on Linux Mint (Cinnamon) 18.3 x64.

**Comment by Penaz91** [comment]
Did you try using the `--nocache` option? From a first analysis it seems a problem with the cache.
If it works, it might be necessary to delete the gcalcli cache.

**Comment by jcrowgey** [comment]
GreatAnubis, reopen if clearing the cache didn't help (I suppose it did).
