### ISSUE TITLE
UnboundLocalError: local variable 'cal_color' referenced before assignment

### ISSUE THREAD

**Issue by dieterdeyke** [insanum/gcalcli#354]
Executing PYTHONPATH=/usr/local/gcalcli/lib/python2.7/site-packages PYTHONIOENCODING=utf_8 /usr/local/gcalcli/bin/gcalcli --calendar 'Dieter Deyke' agenda --tsv 2018-06-23 2018-10-05

results in
Traceback (most recent call last):
  File "/usr/local/gcalcli/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.1.0', 'console_scripts', 'gcalcli')()
  File "build/bdist.linux-x86_64/egg/gcalcli/gcalcli.py", line 1939, in main
  File "build/bdist.linux-x86_64/egg/gcalcli/gcalcli.py", line 1647, in parse_cal_names
UnboundLocalError: local variable 'cal_color' referenced before assignment

This happens on Debian testing with git commit 63ce089b0ad3b02ae2ec516fce9d7d3751c16d70

**Comment by jcrowgey** [comment]
Sorry, I found this with a test I was writing, I shouldn't have pushed the code without finishing the test.  Thanks for saying something!
