### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by mkamensky** [insanum/gcalcli#356]
Got the above when trying to import from STDIN. The full traceback is:
```python
Traceback (most recent call last):
  File "/home/moshe/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.1.0', 'console_scripts', 'gcalcli')()
  File "/home/moshe/.local/lib64/python3.6/site-packages/gcalcli/gcalcli.py", line 2057, in main
    FLAGS.verbose, FLAGS.dump, FLAGS.reminder, FLAGS.file.name)
AttributeError: 'NoneType' object has no attribute 'name'
```
This is from the github version. Problem goes away with a file instead (but then another issue appears, filed separatly). Thanks

**Comment by jcrowgey** [comment]
Thanks, I haven't dug into the ICS import stuff yet.  FWIW, the current master is under a bit of a refactor.  if you don't mind testing, these sorts of bug reports are very helpful.  But if you want something more stable, look in the tagged releases :)

**Comment by jcrowgey** [comment]
Oh shucks, wrong issue number in commit message.
