### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'next'

### ISSUE THREAD

**Issue by mkamensky** [insanum/gcalcli#357]
When trying to import from a file. The traceback is
```python
Traceback (most recent call last):
  File "/home/moshe/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.1.0', 'console_scripts', 'gcalcli')()
  File "/home/moshe/.local/lib64/python3.6/site-packages/gcalcli/gcalcli.py", line 2057, in main
    FLAGS.verbose, FLAGS.dump, FLAGS.reminder, FLAGS.file.name)
  File "/home/moshe/.local/lib64/python3.6/site-packages/gcalcli/gcalcli.py", line 1569, in ImportICS
    v = vobject.readComponents(f).next()
AttributeError: 'generator' object has no attribute 'next'
```
Github version. ics file: [vv.txt](https://github.com/insanum/gcalcli/files/2152627/vv.txt)

**Comment by jcrowgey** [comment]
Yes, py3 changes how generators work.  We need to look up the right way to do this with `six`.  I assume there is some right way.  Thanks!
