### ISSUE TITLE
ModuleNotFoundError: No module named 'oauth2client1412'

### ISSUE THREAD

**Issue by astralspurs** [insanum/gcalcli#391]
After latest update of system packages on Arch, gcalcli is no longer working, giving me this traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/oauth2client/client.py", line 304, in new_from_json
    module_obj = __import__(module_name)
ModuleNotFoundError: No module named 'oauth2client1412'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 2538, in <module>
    BowChickaWowWow()
  File "/usr/bin/gcalcli", line 2436, in BowChickaWowWow
    gcal.AgendaQuery(startText=FLAGS.start, endText=FLAGS.end)
  File "/usr/bin/gcalcli", line 1734, in AgendaQuery
    self._DisplayQueriedEvents(start, end)
  File "/usr/bin/gcalcli", line 1694, in _DisplayQueriedEvents
    eventList = self._SearchForCalEvents(start, end, search)
  File "/usr/bin/gcalcli", line 1631, in _SearchForCalEvents
    work = self._CalService().events().\
  File "/usr/bin/gcalcli", line 670, in _CalService
    http=self._GoogleAuth())
  File "/usr/bin/gcalcli", line 648, in _GoogleAuth
    credentials = storage.get()
  File "/usr/lib/python3.7/site-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/usr/lib/python3.7/site-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/usr/lib/python3.7/site-packages/oauth2client/client.py", line 309, in new_from_json
    module_obj = __import__(module_name)
ModuleNotFoundError: No module named 'oauth2client1412'
```

I've seen the issues #299 and #293, which are similar but I don't understand the instruction. I also don't understand why it's looking for the seemingly modified version of oauth2client named oauth2client1412. Regardless, the package is installed.

```
$ pacman -Q | grep oauth2client
python-oauth2client 4.1.3-1
python2-oauth2client1412 1.4.12-3
```

Some system information:
```
$ uname -a
Linux Antergos 4.19.2-arch1-1-ARCH #1 SMP PREEMPT Tue Nov 13 21:16:19 UTC 2018 x86_64 GNU/Linux
```

**Comment by jcrowgey** [comment]
I suppose we really ought to do some sort of release because almost all of the recent issues reported have been due to very old versions of gcalcli being distributed.  @astralspurs can you install from this repo and re-open this issue if there are problems?  The error you reported, is due to arch pulling an old gcalcli.

**Comment by astralspurs** [comment]
Thanks for the speedy response.

I've cloned the repo and built it using the setup.py file. I'm not so familiar with python and may have missed something here, but I still get a similar problem:
```
$ gcalcli agenda
Traceback (most recent call last):
  File "/home/jesse/.local/lib/python3.7/site-packages/oauth2client/client.py", line 283, in new_from_json
    m = __import__(module)
ModuleNotFoundError: No module named 'oauth2client1412'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.0.0a5', 'console_scripts', 'gcalcli')()
  File "/usr/lib/python3.7/site-packages/gcalcli-4.0.0a5-py3.7.egg/gcalcli/gcalcli.py", line 1611, in main
  File "/usr/lib/python3.7/site-packages/gcalcli-4.0.0a5-py3.7.egg/gcalcli/gcalcli.py", line 1167, in AgendaQuery
  File "/usr/lib/python3.7/site-packages/gcalcli-4.0.0a5-py3.7.egg/gcalcli/gcalcli.py", line 1146, in _display_queried_events
  File "/usr/lib/python3.7/site-packages/gcalcli-4.0.0a5-py3.7.egg/gcalcli/gcalcli.py", line 1101, in _search_for_events
  File "/usr/lib/python3.7/site-packages/gcalcli-4.0.0a5-py3.7.egg/gcalcli/gcalcli.py", line 220, in _cal_service
  File "/usr/lib/python3.7/site-packages/gcalcli-4.0.0a5-py3.7.egg/gcalcli/gcalcli.py", line 198, in _google_auth
  File "/home/jesse/.local/lib/python3.7/site-packages/oauth2client/client.py", line 374, in get
    return self.locked_get()
  File "/home/jesse/.local/lib/python3.7/site-packages/oauth2client/file.py", line 79, in locked_get
    credentials = Credentials.new_from_json(content)
  File "/home/jesse/.local/lib/python3.7/site-packages/oauth2client/client.py", line 287, in new_from_json
    m = __import__(module)
ModuleNotFoundError: No module named 'oauth2client1412'
```
Gcalcli version:
```
$ gcalcli --version
gcalcli v4.0.0a5 (Eric Davis, Brian Hartvigsen, Joshua Crowgey)
```

Output from setup:
```
$ sudo python setup.py install
[sudo] password for jesse: 
running install
running bdist_egg
running egg_info
creating gcalcli.egg-info
writing gcalcli.egg-info/PKG-INFO
writing dependency_links to gcalcli.egg-info/dependency_links.txt
writing entry points to gcalcli.egg-info/entry_points.txt
writing requirements to gcalcli.egg-info/requires.txt
writing top-level names to gcalcli.egg-info/top_level.txt
writing manifest file 'gcalcli.egg-info/SOURCES.txt'
reading manifest file 'gcalcli.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'gcalcli.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/gcalcli
copying gcalcli/printer.py -> build/lib/gcalcli
copying gcalcli/gcalcli.py -> build/lib/gcalcli
copying gcalcli/exceptions.py -> build/lib/gcalcli
copying gcalcli/utils.py -> build/lib/gcalcli
copying gcalcli/argparsers.py -> build/lib/gcalcli
copying gcalcli/__init__.py -> build/lib/gcalcli
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/gcalcli
copying build/lib/gcalcli/printer.py -> build/bdist.linux-x86_64/egg/gcalcli
copying build/lib/gcalcli/gcalcli.py -> build/bdist.linux-x86_64/egg/gcalcli
copying build/lib/gcalcli/exceptions.py -> build/bdist.linux-x86_64/egg/gcalcli
copying build/lib/gcalcli/utils.py -> build/bdist.linux-x86_64/egg/gcalcli
copying build/lib/gcalcli/argparsers.py -> build/bdist.linux-x86_64/egg/gcalcli
copying build/lib/gcalcli/__init__.py -> build/bdist.linux-x86_64/egg/gcalcli
byte-compiling build/bdist.linux-x86_64/egg/gcalcli/printer.py to printer.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/gcalcli/gcalcli.py to gcalcli.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/gcalcli/exceptions.py to exceptions.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/gcalcli/utils.py to utils.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/gcalcli/argparsers.py to argparsers.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/gcalcli/__init__.py to __init__.cpython-37.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/man
creating build/bdist.linux-x86_64/egg/man/man1
copying docs/man1/gcalcli.1 -> build/bdist.linux-x86_64/egg/man/man1
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying gcalcli.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gcalcli.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gcalcli.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gcalcli.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gcalcli.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gcalcli.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/gcalcli-4.0.0a5-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing gcalcli-4.0.0a5-py3.7.egg
Copying gcalcli-4.0.0a5-py3.7.egg to /usr/lib/python3.7/site-packages
Adding gcalcli 4.0.0a5 to easy-install.pth file
Installing gcalcli script to /usr/bin

Installed /usr/lib/python3.7/site-packages/gcalcli-4.0.0a5-py3.7.egg
Processing dependencies for gcalcli==4.0.0a5
Searching for parsedatetime
Reading https://pypi.org/simple/parsedatetime/
Downloading https://files.pythonhosted.org/packages/e3/b3/02385db13f1f25f04ad7895f35e9fe3960a4b9d53112775a6f7d63f264b6/parsedatetime-2.4.tar.gz#sha256=3d817c58fb9570d1eec1dd46fa9448cd644eeed4fb612684b02dfda3a79cb84b
Best match: parsedatetime 2.4
Processing parsedatetime-2.4.tar.gz
Writing /tmp/easy_install-py8u9ppo/parsedatetime-2.4/setup.cfg
Running parsedatetime-2.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-py8u9ppo/parsedatetime-2.4/egg-dist-tmp-19zbk1ih
no previously-included directories found matching '.DS_Store'
zip_safe flag not set; analyzing archive contents...
Moving parsedatetime-2.4-py3.7.egg to /usr/lib/python3.7/site-packages
Adding parsedatetime 2.4 to easy-install.pth file

Installed /usr/lib/python3.7/site-packages/parsedatetime-2.4-py3.7.egg
Searching for future
Reading https://pypi.org/simple/future/
Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz#sha256=67045236dcfd6816dc439556d009594abf643e5eb48992e36beac09c2ca659b8
Best match: future 0.17.1
Processing future-0.17.1.tar.gz
Writing /tmp/easy_install-_3o132v8/future-0.17.1/setup.cfg
Running future-0.17.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_3o132v8/future-0.17.1/egg-dist-tmp-cuo8vk3z
warning: no files found matching '*.au' under directory 'tests'
warning: no files found matching '*.gif' under directory 'tests'
warning: no files found matching '*.txt' under directory 'tests'
zip_safe flag not set; analyzing archive contents...
future.backports.test.__pycache__.ssl_servers.cpython-37: module references __file__
future.backports.test.__pycache__.support.cpython-37: module references __file__
future.standard_library.__pycache__.__init__.cpython-37: module references __file__
future.standard_library.__pycache__.__init__.cpython-37: module references __path__
future.utils.__pycache__.__init__.cpython-37: module MAY be using inspect.stack
past.builtins.__pycache__.misc.cpython-37: module MAY be using inspect.stack
past.translation.__pycache__.__init__.cpython-37: module references __file__
past.translation.__pycache__.__init__.cpython-37: module references __path__
creating /usr/lib/python3.7/site-packages/future-0.17.1-py3.7.egg
Extracting future-0.17.1-py3.7.egg to /usr/lib/python3.7/site-packages
Adding future 0.17.1 to easy-install.pth file
Installing futurize script to /usr/bin
Installing pasteurize script to /usr/bin

Installed /usr/lib/python3.7/site-packages/future-0.17.1-py3.7.egg
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for oauth2client==4.1.3
Best match: oauth2client 4.1.3
Adding oauth2client 4.1.3 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for httplib2==0.11.3
Best match: httplib2 0.11.3
Adding httplib2 0.11.3 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for google-api-python-client==1.7.4
Best match: google-api-python-client 1.7.4
Adding google-api-python-client 1.7.4 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for python-dateutil==2.7.5
Best match: python-dateutil 2.7.5
Adding python-dateutil 2.7.5 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for rsa==4.0
Best match: rsa 4.0
Adding rsa 4.0 to easy-install.pth file
Installing pyrsa-decrypt script to /usr/bin
Installing pyrsa-encrypt script to /usr/bin
Installing pyrsa-keygen script to /usr/bin
Installing pyrsa-priv2pub script to /usr/bin
Installing pyrsa-sign script to /usr/bin
Installing pyrsa-verify script to /usr/bin

Using /usr/lib/python3.7/site-packages
Searching for pyasn1-modules==0.2.2
Best match: pyasn1-modules 0.2.2
Adding pyasn1-modules 0.2.2 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for pyasn1==0.4.4
Best match: pyasn1 0.4.4
Adding pyasn1 0.4.4 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for uritemplate==3.0.0
Best match: uritemplate 3.0.0
Adding uritemplate 3.0.0 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for google-auth-httplib2==0.0.3
Best match: google-auth-httplib2 0.0.3
Adding google-auth-httplib2 0.0.3 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for google-auth==1.6.1
Best match: google-auth 1.6.1
Adding google-auth 1.6.1 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Searching for cachetools==3.0.0
Best match: cachetools 3.0.0
Adding cachetools 3.0.0 to easy-install.pth file

Using /usr/lib/python3.7/site-packages
Finished processing dependencies for gcalcli==4.0.0a5
```
