### ISSUE TITLE
KeyError raised when attempting to edit time and length of event with gcalcli edit

### ISSUE THREAD

**Issue by hammerheadlemon** [insanum/gcalcli#401]
Current master contains a bug where `KeyError` is raised when attempting to edit either the start time ("when") or duration ("length") via `gcalcli edit <EVENT>`.

This is because `self.options['allday']` will only exist if the add parser is used (i.e when using the command `gcalcli add`); it doesn't necessarily make sense to be used in the edit context.

`gcalcli edit` should detect when an event is already an all day event and modify it's "length" question accordingly (minutes or days).

I have uncovered this as part of working on a PR for #399 which is now ready to submit. I won't fix this bug as part of the #399 PR, but will do so separately.

Stacktrace:
```
[N]o [s]ave [q]uit [t]itle [l]ocation [w]hen len[g]th [r]eminder [c]olor [d]escr: w
When: 20 Jan
Traceback (most recent call last):
  File "/home/lemon/.virtualenvs/gcalcli/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli', 'console_scripts', 'gcalcli')()
  File "/home/lemon/code/opensource/gcalcli/gcalcli/gcalcli.py", line 1733, in main
    end=FLAGS.end)
  File "/home/lemon/code/opensource/gcalcli/gcalcli/gcalcli.py", line 1341, in ModifyEvents
    self.now, eventList, yearDate=True, work=work)
  File "/home/lemon/code/opensource/gcalcli/gcalcli/gcalcli.py", line 1078, in _iterate_events
    work(event)
  File "/home/lemon/code/opensource/gcalcli/gcalcli/gcalcli.py", line 997, in _edit_event
    val, length, self.options['allday'])
KeyError: 'allday'
```

**Comment by jcrowgey** [comment]
I think you did end up fixing it in #399.  Thanks @hammerheadlemon
