### ISSUE TITLE
provide better description how to obtain the OAuth2 token

### ISSUE THREAD

**Issue by E3V3A** [insanum/gcalcli#421]
please provide a better README description on how to obtain the OAuth2 token

**Comment by jcrowgey** [comment]
If all goes according to plan, it should be relatively seamless: invoking gcalcli without the token should start a browser to ask you for one.

If you've got details about what went wrong for you---what information you would have like to have seen---that would be amazing!

PRs accepted ;)

**Comment by ricardoamaro** [comment]
I was having trouble getting auth to work:
```
~$ gcalcli agenda
Traceback (most recent call last):
  File "/home/ricardo/.pyenv/versions/3.5.2/bin/gcalcli", line 10, in <module>
    sys.exit(main())
  File "/home/ricardo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/gcalcli/cli.py", line 147, in main
    cal_names=cal_names, printer=printer, **vars(parsed_args)
  File "/home/ricardo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/gcalcli/gcal.py", line 66, in __init__
    self._get_cached()
  File "/home/ricardo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/gcalcli/gcal.py", line 185, in _get_cached
    self.all_cals = self.cache['all_cals']
KeyError: 'all_cals'
```

Then I got it working by disabling cache:
```
$ gcalcli agenda --nocache
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?access_typ....................
```

Hope it help.

**Comment by dbarnett** [comment]
I think the current README has complete instructions now (although the process could certainly be streamlined still).
