### ISSUE TITLE
Calendars with '#' in names are not parsed correctly

### ISSUE THREAD

**Issue by edjacks** [insanum/gcalcli#427]
When issuing a call to retrieve the agenda for a calendar with a '#' symbol in its name, the parse_cal_names in cli.py assumes the '#' is used to identify some color.

gcalcli --calendar="SunSeeker #3" agenda
Traceback (most recent call last):
  File "/Users/user/files/personal/2019/20190227__gcalcli/venv/bin/gcalcli", line 11, in <module>
    sys.exit(main())
  File "/Users/user/files/personal/2019/20190227__gcalcli/venv/lib/python3.7/site-packages/gcalcli/cli.py", line 145, in main
    cal_names = parse_cal_names(parsed_args.calendar)
  File "/Users/user/files/personal/2019/20190227__gcalcli/venv/lib/python3.7/site-packages/gcalcli/cli.py", line 53, in parse_cal_names
    cal_color = valid_color_name(parts[1])
  File "/Users/user/files/personal/2019/20190227__gcalcli/venv/lib/python3.7/site-packages/gcalcli/printer.py", line 51, in valid_color_name
    raise argparse.ArgumentTypeError('%s is not a valid color' % value)
argparse.ArgumentTypeError: 3 is not a valid color

**Comment by dbarnett** [comment]
Huh yeah, that's annoying, impossible to reference such calendar names currently...

It could definitely have more clever heuristics and say "3 isn't a valid color name, so try treating `#3` as part of the calendar name instead of blowing up with a "parsing error".

OTOH, that still leaves ambiguity in the general case, if there could be cases where "mycal#green" could refer to a calendar literally named "mycal#green" OR a calendar named "mycal" that should be colored green. Possibly it could accept backslash-escaped `mycal\#green` to indicate a literal # that should never be parsed as a color separator? I should probably just focus on the straightforward case here and leave that general case alone, but still I'm a little hesitant to dive into improving heuristics without understanding how a general solution should look...
