### ISSUE TITLE
error after upgrade

### ISSUE THREAD

**Issue by focus85** [insanum/gcalcli#429]
does anyone have this issue and how did you fix it. Thanks 

# gcalcli calw
Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.0.4', 'console_scripts', 'gcalcli')()
  File "/usr/lib/python3.7/site-packages/gcalcli/cli.py", line 147, in main
    cal_names=cal_names, printer=printer, **vars(parsed_args)
  File "/usr/lib/python3.7/site-packages/gcalcli/gcal.py", line 67, in __init__
    self._get_cached()
  File "/usr/lib/python3.7/site-packages/gcalcli/gcal.py", line 196, in _get_cached
    self.all_cals = self.cache['all_cals']

**Comment by jcrowgey** [comment]
```shell
rm ~/.gcalcli_cache
```

An unfortunate side effect of making all of the code and variable names in a consistent, pythonic style was that we broke your local cache.  Alas, I wish I had realized it before I released, I would have added versioning to the cache in order to make this seamless.

**Comment by focus85** [comment]
Deleting .gcalclifc fix this issue.
