### ISSUE TITLE
gcalcli list crash.

### ISSUE THREAD

**Issue by ZaxonXP** [insanum/gcalcli#432]
Installed latest from the git, no errors during installation.
[gcalcli_install_log.txt](https://github.com/insanum/gcalcli/files/2966122/gcalcli_install_log.txt)

then I tried `gcalcli calw`:

```
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.0.4', 'console_scripts', 'gcalcli')()
  File "build/bdist.linux-i686/egg/gcalcli/cli.py", line 147, in main
  File "build/bdist.linux-i686/egg/gcalcli/gcal.py", line 67, in __init__
  File "build/bdist.linux-i686/egg/gcalcli/gcal.py", line 196, in _get_cached
```

and `gcalcli list` -> the same result.

1) What do I miss?
2) How to uninstall the GIT version so I could use the one from Debian repo?

Regards,
Piotr

**Comment by jcrowgey** [comment]
Unfortunately, we made an error and didn't include a cache buster in the upgrade which standardized our option flags.  It appears that your error is related to that.  Can you remove the ~/.gcaclcli_cache file and give things another try?

**Comment by stevensonmt** [comment]
Had the same issue. removing `~/.gcalcli_cache` resolved the issue for me.
