### ISSUE TITLE
Unicode Characters Are Not Parsed Correctly

### ISSUE THREAD

**Issue by parhamdoustdar** [insanum/gcalcli#433]
This might be related to #427, but I'm not sure.

I have an event in my calendar that has a colleague's name, "Júlio" in it. Now, whenever I try to get the agenda, I get this error:

```
Traceback (most recent call last):
  File "/Users/pdoustdar/Library/Python/2.7/bin/gcalcli", line 11, in <module>
    sys.exit(main())
  File "/Users/pdoustdar/Library/Python/2.7/lib/python/site-packages/gcalcli/cli.py", line 155, in main
    gcal.AgendaQuery(start=parsed_args.start, end=parsed_args.end)
  File "/Users/pdoustdar/Library/Python/2.7/lib/python/site-packages/gcalcli/gcal.py", line 1177, in AgendaQuery
    return self._display_queried_events(start, end)
  File "/Users/pdoustdar/Library/Python/2.7/lib/python/site-packages/gcalcli/gcal.py", line 1161, in _display_queried_events
    return self._iterate_events(start, event_list, year_date=year_date)
  File "/Users/pdoustdar/Library/Python/2.7/lib/python/site-packages/gcalcli/gcal.py", line 1038, in _iterate_events
    self._PrintEvent(event, prefix)
  File "/Users/pdoustdar/Library/Python/2.7/lib/python/site-packages/gcalcli/gcal.py", line 719, in _PrintEvent
    eventColor
  File "/Users/pdoustdar/Library/Python/2.7/lib/python/site-packages/gcalcli/printer.py", line 91, in msg
    file.write(_u(msg))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 23: ordinal not in range(128)
```

This is a guess though, I can't see what the exactly response is to see what is on character number 23.

**Comment by jcrowgey** [comment]
I'm guessing you don't have a UTF-8 environment, and that's why you get the ascii codec even when not using a pipe.  In any case, your issue is more closely related to #335 than to #427.  I'm closing this as a duplicate, but please reopen if there's actually anything new here that I'm missing.

**Comment by parhamdoustdar** [comment]
Thanks. I was redirecting stdout to a file and didn't think that would be related, but with your explanation it makes sense.
