### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 33: ordinal not in range(128)

### ISSUE THREAD

**Issue by aristosv** [insanum/gcalcli#455]
I am trying to export the results of the commands I run but there's an issue.

I tried this

`gcalcli agenda "`date -d 'now'`" "`date -d 'now + 24 hours'`" >> export`

and I got this

```
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.1.1', 'console_scripts', 'gcalcli')()
  File "build/bdist.linux-x86_64/egg/gcalcli/cli.py", line 155, in main
  File "build/bdist.linux-x86_64/egg/gcalcli/gcal.py", line 1176, in AgendaQuery
  File "build/bdist.linux-x86_64/egg/gcalcli/gcal.py", line 1160, in _display_queried_events
  File "build/bdist.linux-x86_64/egg/gcalcli/gcal.py", line 1029, in _iterate_events
  File "build/bdist.linux-x86_64/egg/gcalcli/gcal.py", line 693, in _PrintEvent
  File "build/bdist.linux-x86_64/egg/gcalcli/printer.py", line 91, in msg
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 33: ordinal not in range(128)

```
and then i tried this

`gcalcli agenda "`date -d 'now'`" "`date -d 'now + 24 hours'`" | tee -a output.txt`

and i got this

```
          Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.1.1', 'console_scripts', 'gcalcli')()
  File "build/bdist.linux-x86_64/egg/gcalcli/cli.py", line 155, in main
  File "build/bdist.linux-x86_64/egg/gcalcli/gcal.py", line 1176, in AgendaQuery
  File "build/bdist.linux-x86_64/egg/gcalcli/gcal.py", line 1160, in _display_queried_events
  File "build/bdist.linux-x86_64/egg/gcalcli/gcal.py", line 1029, in _iterate_events
  File "build/bdist.linux-x86_64/egg/gcalcli/gcal.py", line 693, in _PrintEvent
  File "build/bdist.linux-x86_64/egg/gcalcli/printer.py", line 91, in msg
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 33: ordinal not in range(128)
```
What I'm I doing wrong here?

**Comment by aristosv** [comment]
I did this and it worked

`PYTHONIOENCODING=utf8 gcalcli agenda --tsv "$datenow" "$date24hrs"`
