### ISSUE TITLE
TypeError: sequence item 0: expected str instance, bytes found

### ISSUE THREAD

**Issue by PhilHudson** [insanum/gcalcli#465]
Installed with 'sudo pip3 install gcalcli'. First run generates a token and outputs "Authentication successful', then dumps a stack trace ending with the subject line.

**Comment by PhilHudson** [comment]
Stack trace:

<code>
Authentication successful.
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/gcalcli/cli.py", line 147, in main
    cal_names=cal_names, printer=printer, **vars(parsed_args)
  File "/usr/local/lib/python3.4/dist-packages/gcalcli/gcal.py", line 66, in __init__
    self._get_cached()
  File "/usr/local/lib/python3.4/dist-packages/gcalcli/gcal.py", line 193, in _get_cached
    self.get_cal_service().calendarList().list()
  File "/usr/local/lib/python3.4/dist-packages/gcalcli/gcal.py", line 157, in get_cal_service
    http=self._google_auth())
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/discovery.py", line 224, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/discovery.py", line 274, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1138, in request
    headers = self._normalize_headers(headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1106, in _normalize_headers
    return _normalize_headers(headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 194, in _normalize_headers
    return dict([ (key.lower(), NORMALIZE_SPACE.sub(value, ' ').strip())  for (key, value) in headers.items()])
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 194, in <listcomp>
    return dict([ (key.lower(), NORMALIZE_SPACE.sub(value, ' ').strip())  for (key, value) in headers.items()])
TypeError: sequence item 0: expected str instance, bytes found

</code>

**Comment by PhilHudson** [comment]
Try again...
<pre>
 Authentication successful.
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/gcalcli/cli.py", line 147, in main
    cal_names=cal_names, printer=printer, **vars(parsed_args)
  File "/usr/local/lib/python3.4/dist-packages/gcalcli/gcal.py", line 66, in __init__
    self._get_cached()
  File "/usr/local/lib/python3.4/dist-packages/gcalcli/gcal.py", line 193, in _get_cached
    self.get_cal_service().calendarList().list()
  File "/usr/local/lib/python3.4/dist-packages/gcalcli/gcal.py", line 157, in get_cal_service
    http=self._google_auth())
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/discovery.py", line 224, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/discovery.py", line 274, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1138, in request
    headers = self._normalize_headers(headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1106, in _normalize_headers
    return _normalize_headers(headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 194, in _normalize_headers
    return dict([ (key.lower(), NORMALIZE_SPACE.sub(value, ' ').strip())  for (key, value) in headers.items()])
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 194, in <listcomp>
    return dict([ (key.lower(), NORMALIZE_SPACE.sub(value, ' ').strip())  for (key, value) in headers.items()])
TypeError: sequence item 0: expected str instance, bytes found

</pre>

**Comment by PhilHudson** [comment]
Linux asdf 3.16.0-8-amd64 #1 SMP Debian 3.16.64-2 (2019-04-01) x86_64 GNU/Linux

**Comment by PhilHudson** [comment]
<pre>
python --version
Python 2.7.9

python3 --version
Python 3.4.2
</pre>

**Comment by jcrowgey** [comment]
> ```expected str instance, bytes found```

That's a classic py2 vs py3 error message.  I wonder if something in setup.py isn't written correctly for your setuptools.  I can install gcalcli with pip3 on my debian system without an error, so I may need some help figuring out how to repro this.

**Comment by PhilHudson** [comment]
OK, I need to upgrade my distro I guess.
