### ISSUE TITLE
Gcalcli fails to run on Android/Termux

### ISSUE THREAD

**Issue by deftdawg** [insanum/gcalcli#481]
Below is the stack trace, from what I've googled so far some platforms don't support "nl_langinfo"...  Posted here in case someone knows a work around or others encounters this problem in the future.

```
gcalcli --help
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/gcalcli", line 10, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/gcalcli/cli.py", line 92, in main
    parser = get_argument_parser()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/gcalcli/deprecations.py", line 101, in wrapped
    parser = getter_func()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/gcalcli/argparsers.py", line 250, in get_argument_parser
    output_parser = get_output_parser(parents=[color_parser])
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/gcalcli/argparsers.py", line 122, in get_output_parser
    has_24_hours = locale_has_24_hours()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/gcalcli/argparsers.py", line 97, in locale_has_24_hours
    formatted = t.strftime(locale.nl_langinfo(locale.T_FMT))
AttributeError: module 'locale' has no attribute 'nl_langinfo'
$ python --version
Python 3.7.4
```

**Comment by jcrowgey** [comment]
I like that you're using gcalcli on Termux.  Thanks for the bug report.  Are you able to pull build from git?  If so, can you comfirm that this branch[1] fixes your issue?

[1]: https://github.com/insanum/gcalcli/tree/bugfix/481

**Comment by deftdawg** [comment]
That seems to have resolved it... Here's the steps I followed

```bash
git clone https://github.com/insanum/gcalcli
cd gcalcli/
git checkout bugfix/481
gcalcli # old one with the error
pip uninstall gcalcli # remove it
python setup.py install # install new
gcalcli # looks good
```

Thanks for the patch.

Now to figure out how to use it.

**Comment by jcrowgey** [comment]
I've merged that branch to master.  I can release a bugfix to pypi as 4.2.1 if that's helpful.  Otherwise, if you can use git (which is seems like you can), then I'll probably wait and collect a few more bugfixes before I release.

**Comment by deftdawg** [comment]
I'm using the git, so no biggie for me.  Everything seems to work great after the fix, did my oauth, set my default calendar and then quick added some appointments. 

Next step is to scrape some dates using pup and feed them in.

Thanks for the quick fix 😄
