### ISSUE TITLE
getting this error since a few days 

### ISSUE THREAD

**Issue by kurokirasama** [insanum/gcalcli#503]
Hello, I'm getting this error since a few days. Already tried reinstalling, apt and source versions.

```
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.2.0', 'console_scripts', 'gcalcli')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/gcalcli/cli.py", line 30, in <module>
  File "build/bdist.linux-x86_64/egg/gcalcli/argparsers.py", line 8, in <module>
ImportError: cannot import name get_terminal_size

```

Also tried on python3:
```
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.2.0', 'console_scripts', 'gcalcli')()
  File "/usr/local/lib/python3.6/dist-packages/gcalcli-4.2.0-py3.6.egg/gcalcli/cli.py", line 147, in main
  File "/usr/local/lib/python3.6/dist-packages/gcalcli-4.2.0-py3.6.egg/gcalcli/gcal.py", line 67, in __init__
  File "/usr/local/lib/python3.6/dist-packages/gcalcli-4.2.0-py3.6.egg/gcalcli/gcal.py", line 186, in _get_cached
KeyError: 'all_cals'

```
How do I uninstall the source version now?_?

**Comment by jcrowgey** [comment]
It looks like you just need to drop your ~/.gcalcli_cache file.
