### ISSUE TITLE
ImportError: cannot import name get_terminal_size

### ISSUE THREAD

**Issue by marekkowalczyk** [insanum/gcalcli#521]
Just after installing via `~ pip install gcalcli` I got

~~~
~ gcalcli
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 5, in <module>
    from gcalcli.cli import main
  File "/usr/local/lib/python2.7/site-packages/gcalcli/cli.py", line 30, in <module>
    from gcalcli.argparsers import get_argument_parser, handle_unparsed
  File "/usr/local/lib/python2.7/site-packages/gcalcli/argparsers.py", line 8, in <module>
    from shutil import get_terminal_size
ImportError: cannot import name get_terminal_size
~~~
on 

~~~
Software:

    System Software Overview:

      System Version: macOS 10.14.6 (18G3020)
      Kernel Version: Darwin 18.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: MKO
      User Name: Marek Kowalczyk (marekkowalczyk)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3 days 16:12
~~~

**Comment by jcrowgey** [comment]
Upgrade to python3

**Comment by aliveawakened** [comment]
MacOS and Raspberry Pi both have Pythons 2 and 3 install but default to Python 2. In /usr/local/bin/gcalcli, change the first line from `#!/usr/bin/python` to `#!/usr/bin/python3` to force it to use Python 3.

**Comment by jcrowgey** [comment]
Or install with pip3
