### ISSUE TITLE
SSL Validation Fails (Windows 10, Python 3.7.0)

### ISSUE THREAD

**Issue by aliveawakened** [insanum/gcalcli#524]
Get the following traceback after authenticating with Google. `httplib2` version is 0.17.0. 

```
Traceback (most recent call last):
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python37\Scripts\gcalcli.exe\__main__.py", line 7, in <module>
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\gcalcli\cli.py", line 147, in main
    cal_names=cal_names, printer=printer, **vars(parsed_args)
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\gcalcli\gcal.py", line 67, in __init__
    self._get_cached()
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\gcalcli\gcal.py", line 194, in _get_cached
    self.get_cal_service().calendarList().list()
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\gcalcli\gcal.py", line 158, in get_cal_service
    http=self._google_auth())
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\gcalcli\gcal.py", line 147, in _google_auth
    Namespace(**self.options)
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\oauth2client\tools.py", line 243, in run_flow
    credential = flow.step2_exchange(code, http=http)
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\oauth2client\client.py", line 2054, in step2_exchange
    http, self.token_uri, method='POST', body=body, headers=headers)
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\httplib2\__init__.py", line 1991, in request
    cachekey,
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\httplib2\__init__.py", line 1651, in _request
    conn, request_uri, method, body, headers
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\httplib2\__init__.py", line 1557, in _conn_request
    conn.connect()
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\httplib2\__init__.py", line 1326, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)
```

**Comment by aliveawakened** [comment]
Fixed by installing PySSL module:
```
pip install PySSL
```
