### ISSUE TITLE
gcalcli + python 3.8.2 crashes on locale module

### ISSUE THREAD

**Issue by amitkeret** [insanum/gcalcli#526]
Windows 10
Previously working on python 3.7
Fresh (chocolatey) installs of Python 3.8.2 + pip 19.2.3

```
> pip install gcalcli
Collecting gcalcli
...
Successfully installed cachetools-4.0.0 certifi-2019.11.28 chardet-3.0.4 gcalcli-4.2.0 google-api-core-1.16.0 google-api-python-client-1.8.0 google-auth-1.12.0 google-auth-httplib2-0.0.3 googleapis-common-protos-1.51.0 httplib2-0.17.0 idna-2.9 oauth2client-4.1.3 parsedatetime-2.5 protobuf-3.11.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 python-dateutil-2.8.1 pytz-2019.3 requests-2.23.0 rsa-4.0 six-1.14.0 uritemplate-3.0.1 urllib3-1.25.8
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

> gcalcli
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\gcalcli.exe\__main__.py", line 9, in <module>
  File "c:\python38\lib\site-packages\gcalcli\cli.py", line 92, in main
    parser = get_argument_parser()
  File "c:\python38\lib\site-packages\gcalcli\deprecations.py", line 101, in wrapped
    parser = getter_func()
  File "c:\python38\lib\site-packages\gcalcli\argparsers.py", line 250, in get_argument_parser
    output_parser = get_output_parser(parents=[color_parser])
  File "c:\python38\lib\site-packages\gcalcli\argparsers.py", line 122, in get_output_parser
    has_24_hours = locale_has_24_hours()
  File "c:\python38\lib\site-packages\gcalcli\argparsers.py", line 97, in locale_has_24_hours
    formatted = t.strftime(locale.nl_langinfo(locale.T_FMT))
AttributeError: module 'locale' has no attribute 'nl_langinfo'
```

**Comment by noreallyimfine** [comment]
I ran into the same issue.

Google led me to this issue (https://github.com/ibis-project/ibis/issues/844)  in the GitHub repo for ibis. That issue seems to say nl_langinfo is not available on Windows. 

Going to try to look into how they resolved it there.

**Comment by jcrowgey** [comment]
f6f181d34258180ef854b2ff366377e08c75dfcf

#481
