### ISSUE TITLE
How do I run this after installing from the master branch?

### ISSUE THREAD

**Issue by gregcman** [insanum/gcalcli#551]
```
greg@spectre:~/src/gcalcli$ python3 gcalcli
/usr/bin/python3: can't find '__main__' module in 'gcalcli'
```

**Comment by gregcman** [comment]
Also:
```
greg@spectre:~$ gcalcli list
Traceback (most recent call last):
  File "/home/greg/.local/bin/gcalcli", line 33, in <module>
    sys.exit(load_entry_point('gcalcli==4.3.0', 'console_scripts', 'gcalcli')())
  File "/home/greg/.local/lib/python3.6/site-packages/gcalcli/cli.py", line 144, in main
    cal_names=cal_names, printer=printer, **vars(parsed_args)
  File "/home/greg/.local/lib/python3.6/site-packages/gcalcli/gcal.py", line 67, in __init__
    self._get_cached()
  File "/home/greg/.local/lib/python3.6/site-packages/gcalcli/gcal.py", line 186, in _get_cached
    self.all_cals = self.cache['all_cals']
KeyError: 'all_cals'
greg@spectre:~$ 

```

**Comment by gregcman** [comment]
Never mind, got it to work with `--refresh`
