### ISSUE TITLE
FileNotFoundError on first run with custom browser command

### ISSUE THREAD

**Issue by borisjoffe** [insanum/gcalcli#556]
Steps to reproduce:
* install `gcalcli`
* run `BROWSER="/usr/bin/chromium --user-data-dir=$HOME/.config/chromium/"` (sets default browser to chromium with specified data directory)
* run `gcalcli list`

Expected behavior:
* browser opens to OAuth page

Actual behavior:
```bash
Traceback (most recent call last):
  File "/bin/gcalcli", line 33, in <module>
    sys.exit(load_entry_point('gcalcli==4.3.0', 'console_scripts', 'gcalcli')())
  File "/usr/lib/python3.8/site-packages/gcalcli/cli.py", line 143, in main
    gcal = GoogleCalendarInterface(
  File "/usr/lib/python3.8/site-packages/gcalcli/gcal.py", line 67, in __init__
    self._get_cached()
  File "/usr/lib/python3.8/site-packages/gcalcli/gcal.py", line 194, in _get_cached
    self.get_cal_service().calendarList().list()
  File "/usr/lib/python3.8/site-packages/gcalcli/gcal.py", line 158, in get_cal_service
    http=self._google_auth())
  File "/usr/lib/python3.8/site-packages/gcalcli/gcal.py", line 139, in _google_auth
    credentials = tools.run_flow(
  File "/usr/lib/python3.8/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/oauth2client/tools.py", line 223, in run_flow
    webbrowser.open(authorize_url, new=1, autoraise=True)
  File "/usr/lib/python3.8/webbrowser.py", line 86, in open
    if browser.open(url, new, autoraise):
  File "/usr/lib/python3.8/webbrowser.py", line 275, in open
    success = self._invoke(args, True, autoraise, url)
  File "/usr/lib/python3.8/webbrowser.py", line 237, in _invoke
    p = subprocess.Popen(cmdline, close_fds=True, stdin=inout,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/chromium --user-data-dir=/home/<yourusername>/.config/chromium/'
```

**Comment by michaelmhoffman** [comment]
It looks like the Python `webbrowser` module expects `BROWSER` to be a single file and not have extra parameters. I don't think this is a bug. I would suggest creating a shell script that runs chromium with the options you want and setting `BROWSER` to that.

**Comment by borisjoffe** [comment]
Actually, after some more research, it looks like the `BROWSER` variable needs to specify `%s` to work. Otherwise, it's treated as a single command.

> If the environment variable BROWSER exists, it is interpreted as the os.pathsep-separated list of browsers to try ahead of the platform defaults. When the value of a list part contains the string %s, then it is interpreted as a literal browser command line to be used with the argument URL substituted for %s; if the part does not contain %s, it is simply interpreted as the name of the browser to launch.

https://docs.python.org/3.8/library/webbrowser.html#module-webbrowser

Running:
`BROWSER="chromium --user-data-dir=$HOME/.config/chromium/ %s"`
fixes the issue

You're right that it's not a gcalcli bug
