### ISSUE TITLE
Unicode conversion still broken (Windows 10 Python 3.7 gcalcli 4.2.0)

### ISSUE THREAD

**Issue by ghost** [insanum/gcalcli#560]
Running gcalcli 4.2.0 in Python 3.7.0 in Windows 10, trying to import a calendar saved from Outlook 2013 into Google Calendar. Note that importing via Google Calendar's import function works just fine.

```
PS C:\Users\s4b4211> gcalcli --calendar='Work Schedule' import -v 'P:\Documents\Buehler Steven W. Calendar.ics'
Traceback (most recent call last):
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\s4b4211\AppData\Local\Programs\Python\Python37\Scripts\gcalcli.exe\__main__.py", line 7, in <module>
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\gcalcli\cli.py", line 230, in main
    parsed_args.reminders, parsed_args.file
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\gcalcli\gcal.py", line 1549, in ImportICS
    v = next(vobject.readComponents(f))
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\vobject\base.py", line 1089, in readComponents
    for line, n in getLogicalLines(stream, allowQP):
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\site-packages\vobject\base.py", line 869, in getLogicalLines
    val = fp.read(-1)
  File "c:\users\s4b4211\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 72838: character maps to <undefined>
```

**Comment by dbarnett** [comment]
Duping to #375.
