### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' 

### ISSUE THREAD

**Issue by djs45** [insanum/gcalcli#569]
Hello
I have error when use gcalcli
Please help me : 

pi@raspberrypi:~/gcalcli $ gcalcli --cal="AGENDA COMMUN" agenda

Sat Oct 03           Filles seb

Tue Oct 06Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.0.0a5', 'console_scripts', 'gcalcli')()
  File "build/bdist.linux-armv7l/egg/gcalcli/gcalcli.py", line 1611, in main
  File "build/bdist.linux-armv7l/egg/gcalcli/gcalcli.py", line 1167, in AgendaQuery
  File "build/bdist.linux-armv7l/egg/gcalcli/gcalcli.py", line 1151, in _display_queried_events
  File "build/bdist.linux-armv7l/egg/gcalcli/gcalcli.py", line 1033, in _iterate_events
  File "build/bdist.linux-armv7l/egg/gcalcli/gcalcli.py", line 729, in _PrintEvent
  File "build/bdist.linux-armv7l/egg/gcalcli/printer.py", line 91, in msg
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 16: ordinal not in range(128)
p

**Comment by dbarnett** [comment]
Can you still repro? I can't with the latest gcalcli.
