### ISSUE TITLE
Error with rsa version after upgrading to Ubuntu 20.10

### ISSUE THREAD

**Issue by pmahnke** [insanum/gcalcli#571]
I am getting the following error after upgrading from Ubuntu 20.04 to 20.10.

```
Traceback (most recent call last):
  File "/home/peter/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/home/peter/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/peter/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (rsa 4.6 (/home/peter/.local/lib/python3.8/site-packages), Requirement.parse('rsa<4.1,>=3.1.4'), {'google-auth'})
```

the version of rsa is 4.0

Any help would be appreciated

**Comment by dbarnett** [comment]
I suspect this is no longer an issue?

I'll close it in a few days if I don't hear otherwise (but still feel free to report again / reopen if needed).
