### ISSUE TITLE
gcalcli stopped working today

### ISSUE THREAD

**Issue by kurokirasama** [insanum/gcalcli#638]
I'm getting this error when trying to do anything:
```
Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.2.0', 'console_scripts', 'gcalcli')()
  File "/home/kira/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 486, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kira/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2867, in load_entry_point
    return ep.load()
  File "/home/kira/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2471, in load
    return self.resolve()
  File "/home/kira/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/gcalcli/cli.py", line 30, in <module>
    from gcalcli.argparsers import get_argument_parser, handle_unparsed
  File "/usr/lib/python3/dist-packages/gcalcli/argparsers.py", line 7, in <module>
    from oauth2client import tools
  File "/usr/lib/python3/dist-packages/oauth2client/tools.py", line 34, in <module>
    from oauth2client import client
  File "/usr/lib/python3/dist-packages/oauth2client/client.py", line 45, in <module>
    from oauth2client import crypt
  File "/usr/lib/python3/dist-packages/oauth2client/crypt.py", line 45, in <module>
    from oauth2client import _openssl_crypt
  File "/usr/lib/python3/dist-packages/oauth2client/_openssl_crypt.py", line 16, in <module>
    from OpenSSL import crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.2.0', 'console_scripts', 'gcalcli')()
  File "/home/kira/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 486, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kira/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2867, in load_entry_point
    return ep.load()
  File "/home/kira/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2471, in load
    return self.resolve()
  File "/home/kira/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/gcalcli/cli.py", line 30, in <module>
    from gcalcli.argparsers import get_argument_parser, handle_unparsed
  File "/usr/lib/python3/dist-packages/gcalcli/argparsers.py", line 7, in <module>
    from oauth2client import tools
  File "/usr/lib/python3/dist-packages/oauth2client/tools.py", line 34, in <module>
    from oauth2client import client
  File "/usr/lib/python3/dist-packages/oauth2client/client.py", line 45, in <module>
    from oauth2client import crypt
  File "/usr/lib/python3/dist-packages/oauth2client/crypt.py", line 45, in <module>
    from oauth2client import _openssl_crypt
  File "/usr/lib/python3/dist-packages/oauth2client/_openssl_crypt.py", line 16, in <module>
    from OpenSSL import crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

```

**Comment by kurokirasama** [comment]
fixed with:
```
pip3 install pyOpenSSL --upgrade
```
