### ISSUE TITLE
--lineart unicode TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by elig0n** [insanum/gcalcli#673]
when running `calm` or `calw` with `--lineart unicode` I get:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/gcalcli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/gcalcli/cli.py", line 174, in main
    gcal.CalQuery(parsed_args.command, start_text=parsed_args.start)
  File "/usr/lib/python3.11/site-packages/gcalcli/gcal.py", line 1264, in CalQuery
    self._GraphEvents(cmd, start, count, event_list)
  File "/usr/lib/python3.11/site-packages/gcalcli/gcal.py", line 474, in _GraphEvents
    self.printer.msg(month_title_top + '\n', color_border)
                     ~~~~~~~~~~~~~~~~^~~~~~
TypeError: can't concat str to bytes                                                                                                                                
```

version:
`gcalcli v4.3.0 (Eric Davis, Brian Hartvigsen, Joshua Crowgey)`
Package `gcalcli-git 4.3.0.r417.ga4ac3e7-1` on Manjaro
`Python 3.11.5`

**Comment by dbarnett** [comment]
Fixed via #582.
