### ISSUE TITLE
oauth2 failing

### ISSUE THREAD

**Issue by ebishi** [insanum/gcalcli#72]
I'm attempting to authenticate with the --noauth_local_webserver switch. After I enter the verification code from Google, I receive the following traceback. I get that the issue is somehow related to SSL, but beyond that, I'm not sure what's going...

Are there additional dependencies which I'm missing?

Traceback (most recent call last):
  File "gcalcli", line 2242, in <module>
    BowChickaWowWow()
  File "gcalcli", line 2091, in BowChickaWowWow
    configFolder=FLAGS.configFolder
  File "gcalcli", line 461, in **init**
    self._GetCached()
  File "gcalcli", line 551, in _GetCached
    calList = self._CalService().calendarList().list().execute()
  File "gcalcli", line 502, in _CalService
    http=self._GoogleAuth(),
  File "gcalcli", line 490, in _GoogleAuth
    storage)
  File "/usr/local/lib/python2.7/site-packages/google_api_python_client-1.1-py2.7.egg/oauth2client/util.py", line 128, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/google_api_python_client-1.1-py2.7.egg/oauth2client/tools.py", line 197, in run
    credential = flow.step2_exchange(code, http=http)
  File "/usr/local/lib/python2.7/site-packages/google_api_python_client-1.1-py2.7.egg/oauth2client/util.py", line 128, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/google_api_python_client-1.1-py2.7.egg/oauth2client/client.py", line 1283, in step2_exchange
    headers=headers)
  File "/usr/local/lib/python2.7/site-packages/httplib2-0.8-py2.7.egg/httplib2/__init__.py", line 1570, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/site-packages/httplib2-0.8-py2.7.egg/httplib2/__init__.py", line 1317, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/site-packages/httplib2-0.8-py2.7.egg/httplib2/__init__.py", line 1252, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/site-packages/httplib2-0.8-py2.7.egg/httplib2/__init__.py", line 1021, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "/usr/local/lib/python2.7/site-packages/httplib2-0.8-py2.7.egg/httplib2/**init**.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "/usr/local/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/ssl.py", line 141, in __init__
    ciphers)
ssl.SSLError: [Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

**Comment by atsepkov** [comment]
FYI, had the same problem on Ubuntu, fixed it as follows:

    chmod 644 /usr/local/lib/python2.7/dist-packages/httplib2-0.8-py2.7.egg/httplib2/cacerts.txt

Posting it here because it took me forever to find where this certificate was stored, and hopefully this will help someone else.
