### ISSUE TITLE
Not yet authenticated after upgrade to 4.5.0, then crash

### ISSUE THREAD

**Issue by ZaxonXP** [insanum/gcalcli#790]
When I upgraded to 4.5.0 I got the message that gcalcli is not authenticated, so I tried to do so. But then I got this error:
```
Not yet authenticated.
Starting auth flow...
NOTE: See https://github.com/insanum/gcalcli/blob/HEAD/docs/api-auth.md for help/troubleshooting.
Now click the link below and follow directions to authenticate.
You will likely see a security warning page and need to click "Advanced" and "Go to gcalcli (unsafe)" to proceed.
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=XXXXXXXXXXX.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A33195%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar&state=4al07gyUtZ4snpeZzsRnvGuA6Vz2ep&access_type=offline
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/gcalcli/auth.py", line 52, in authenticate
    credentials = flow.run_local_server(open_browser=False, port=port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/google_auth_oauthlib/flow.py", line 458, in run_local_server
    self.fetch_token(
  File "/usr/local/lib/python3.11/dist-packages/google_auth_oauthlib/flow.py", line 285, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests_oauthlib/oauth2_session.py", line 381, in fetch_token
    r = self.request(
        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests_oauthlib/oauth2_session.py", line 566, in request
    return super(OAuth2Session, self).request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connection.py", line 767, in _ssl_wrap_socket_and_match_hostname
    context.verify_mode = resolve_cert_reqs(cert_reqs)
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 742, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
  File "/usr/lib/python3.11/ssl.py", line 742, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
  File "/usr/lib/python3.11/ssl.py", line 742, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
  [Previous line repeated 487 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gcalcli/cli.py", line 231, in main
    gcal = GoogleCalendarInterface(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gcalcli/gcal.py", line 87, in __init__
    self._get_cached()
  File "/usr/local/lib/python3.11/dist-packages/gcalcli/gcal.py", line 325, in _get_cached
    self.get_cal_service().calendarList().list(
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gcalcli/gcal.py", line 292, in get_cal_service
    credentials=self._google_auth(),
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gcalcli/gcal.py", line 165, in _google_auth
    self.SetupAuth()
  File "/usr/local/lib/python3.11/dist-packages/gcalcli/gcal.py", line 274, in SetupAuth
    self.credentials = auth.authenticate(
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gcalcli/auth.py", line 61, in authenticate
    raise OSError(
OSError: Failed to fetch credentials. If this is a nonstandard gcalcli install, please try again with a system-installed gcalcli as a workaround.
Details: https://github.com/insanum/gcalcli/issues/735.


```
I am not sure if this is due to my messy Python installation where I installed some packages using pip and the --break-system-packages option. I would like to clean up my Python installation and use virtual anvironment, but I do not know how to do the cleaning correctly. Could you please advise?

**Comment by ZaxonXP** [comment]
Or is this some unexpected bug? How can I fix it?

**Comment by dbarnett** [comment]
Might be able to give a few pointers if you can share OS details, how you installed that instance, and what kinds of packages you're referring to that you might've force installed. If you happen to have hacked any installations for packages in the stack trace, try to clean those up first, but beyond that it's less clear, and one of the big hazards of --break-system-packages is there's no easy way to reverse or inspect it afterwards.

I recently escalated with a fresh issue in urllib3 but the bad news is it's a mysterious error deep in python deps/system and we know almost nothing about what triggers it.

I was really hoping it was isolated to local dev installs and nobody would have that issue if you used a system install…

Duping to https://github.com/insanum/gcalcli/issues/735 for high-level follow-up.

**Comment by ZaxonXP** [comment]
Debian 12 bookworm
What else can it be usefull?

I installed it with this command:
```
        sudo pip3 install gcalcli --upgrade --break-system-packages
```

I remember that few times I used this `--break-system-packages` flag in order to install some missing Python packages using `pip` tool. It was some time ago, so now I do not remember which packages were installed that way. 

But how to find out which packages were installed with this `--break-system-packages` flag?

**Comment by dbarnett** [comment]
Oh, the whole gcalcli you installed that way. Have you tried with pipx? I'd recommend that over smashing it over your system installs:

```shell
$ sudo apt install pipx
$ pipx install gcalcli[vobject]
$ which gcalcli
/home/someuser/.local/bin/gcalcli
$ gcalcli --version
gcalclci 4.5.0
```

**Comment by ZaxonXP** [comment]
OK. I removed the gcalcli using sudo pip uninstall gcalcli then installed as you suggested. Then I got to put ID and secret and authenticate in web browser. Afterwards I got these errors:
```
Not yet authenticated.
Starting auth flow...
NOTE: See https://github.com/insanum/gcalcli/blob/HEAD/docs/api-auth.md for help/troubleshooting.
You'll be asked for a client_id and client_secret that you should have set up for yourself in Google dev console.
Client ID: XXXXX
Client Secret: YYYYYY
Now click the link below and follow directions to authenticate.
You will likely see a security warning page and need to click "Advanced" and "Go to gcalcli (unsafe)" to proceed.
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=1005180736598-mjs63o3a6h4vss4me58tsdepa4q6ov6r.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A41281%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar&state=dLOairt689IPRQOTBjdUWCtTzTm4qX&access_type=offline
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/gcalcli/auth.py", line 52, in authenticate
    credentials = flow.run_local_server(open_browser=False, port=port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/google_auth_oauthlib/flow.py", line 458, in run_local_server
    self.fetch_token(
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/google_auth_oauthlib/flow.py", line 285, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 381, in fetch_token
    r = self.request(
        ^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 566, in request
    return super(OAuth2Session, self).request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/urllib3/connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/urllib3/connection.py", line 871, in _ssl_wrap_socket_and_match_hostname
    context.verify_mode = resolve_cert_reqs(cert_reqs)
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 742, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
  File "/usr/lib/python3.11/ssl.py", line 742, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
  File "/usr/lib/python3.11/ssl.py", line 742, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
  [Previous line repeated 487 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/gcalcli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/gcalcli/cli.py", line 231, in main
    gcal = GoogleCalendarInterface(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/gcalcli/gcal.py", line 87, in __init__
    self._get_cached()
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/gcalcli/gcal.py", line 325, in _get_cached
    self.get_cal_service().calendarList().list(
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/gcalcli/gcal.py", line 292, in get_cal_service
    credentials=self._google_auth(),
                ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/gcalcli/gcal.py", line 165, in _google_auth
    self.SetupAuth()
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/gcalcli/gcal.py", line 274, in SetupAuth
    self.credentials = auth.authenticate(
                       ^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/gcalcli/lib/python3.11/site-packages/gcalcli/auth.py", line 61, in authenticate
    raise OSError(
OSError: Failed to fetch credentials. If this is a nonstandard gcalcli install, please try again with a system-installed gcalcli as a workaround.
Details: https://github.com/insanum/gcalcli/issues/735.
```
Maybe I should try to install 4.4.0 and try to authenticate it, then try to use 4.5.0 as you suggested in the linked issue #735?

**Comment by dbarnett** [comment]
Yeah, sorry for the hassle, disappointing that you're still hitting the recursion errors even in that setup but I'd try authenticating on 4.4.0 next.

When you opened this issue you said it was missing auth when you upgraded to 4.5.0. Was that just from an upgrade from 4.4.0 to 4.5.0, or was something else going on there that might've disrupted the existing auth?

**Comment by dbarnett** [comment]
Another helpful thing to try: after authenticating in 4.4.0, upgrade to 4.5.0, and before running any other commands run `gcalcli util inspect-auth`.
