### ISSUE TITLE
`config edit` can fail with FileNotFoundError

### ISSUE THREAD

**Issue by dbarnett** [insanum/gcalcli#800]
Seems like when the ~/.config/gcalcli dir or whatever platform-specific equivalent doesn't exist yet, `gcalcli config edit` can error out with FileNotFoundError, like:

```shell
$ gcalcli config edit
Launching ~/.config/gcalcli/config.toml in a text editor...Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/gcalcli/cli.py", line 341, in main
    with open(config_filepath, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/someuser/.config/gcalcli/config.toml'
```

Should probably ensure the parent dir is created when running that command. Or otherwise at least give a nicer failure message for that case.

**Comment by dbarnett** [comment]
And while we're at it, this message seems to be missing a newline: `Launching ~/.config/gcalcli/config.toml in a text editor...`
